spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Spring_Board
    username: root
    password: wjdgusdnr0519

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        show-sql: true
        ddl-auto: create
        format_sql: true

logging:
  level:
    org.hibernate: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace